### ISSUE TITLE
Не прописано not null

### ISSUE THREAD

**Issue by AlekseiPavlovskii** [qasmark/TLPractise#2]
https://github.com/qasmark/TLPractise/blob/11f318e4e4adf19fc5bcf05d5f965a6324ae9cce/ThirdTask/dump.sql#L4

Для первичного ключа желательно явно прописать not null

**Comment by AlekseiPavlovskii** [comment]
Аналогичная ошибка в других первичных ключах

**Comment by qasmark** [comment]
Добавил NOT NULL в первичные ключи моделей (сущностей)
