### ISSUE TITLE
Интерфейс.

### ISSUE THREAD

**Issue by yaroslav-hub** [qasmark/TLPractise#6]
Для чего нужен IComparable?

https://github.com/qasmark/TLPractise/blob/96fc1e78d2416e02d4a229f5d8c69c9d0a6eee02/FirstTask/BubbleSort/Program.cs#L8

**Comment by qasmark** [comment]
IComparable используется для сравнения объектов в списков и сортировки элементов в порядке возрастания или убывания. Он определяет метод CompareTo, который позволяет сравнивать текущий объект с другим объектом и возвращать результат сравнения (-1, 0 или 1). В данном случае, метод Sort использует IComparable для сравнения элементов коллекции и их последующей сортировки. При использовании Sort с типом T, который реализует интерфейс IComparable, можно гарантировать правильную сортировку элементов.

https://metanit.com/sharp/tutorial/3.23.php
